# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
sudo: false
cache:
  packages: yes

matrix:
  include:
    - os: linux
      sudo: false
      pandoc_version: 1.19.2.1
    - os: linux
      sudo: false
      pandoc_version: 2.0.4

r:
 - oldrel
 - release

r_github_packages:
  - jimhester/covr

after_success:
  - Rscript -e 'library(covr);codecov()'



