# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
cache: packages

r_github_packages:
  - jimhester/covr

matrix:
  include:
    - pandoc_version: 1.16
    - pandoc_version: 2.0.4

r:
 - oldrel
 - release
 - devel

after_success:
  - Rscript -e 'library(covr);codecov()'
