# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
sudo: false
cache:
  packages: yes

matrix:
  include:
    - os: linux
      sudo: false
      pandoc_version: 1.19.2.1
      addons:
        apt:
          update: true
          packages:
            - libmagick++-dev
            - librsvg2-dev
            - libwebp-dev
            - libpoppler-cpp-dev
            - libtesseract-dev
            - libleptonica-dev
            - tesseract-ocr-eng
            - r-cran-rgdal
            - libfftw3-dev
            - cargo
    - os: linux
      sudo: false
      pandoc_version: 2.0.4

r:
 - oldrel
 - release

r_packages:
  - covr

after_success:
  - Rscript -e 'library(covr);codecov()'



