# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
sudo: false
cache:
  packages: yes

pandoc_version: 1.19.2.1

env:
  - PANDOC_VERSION=default
  - PANDOC_VERSION=latest PATH=$HOME/bin:$PATH

r_github_packages:
  - jimhester/covr

after_success:
  - Rscript -e 'library(covr);codecov()'
